org: lucasxavier000
app: image-analyzis
console: true
service: image-analyzis
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - rekognition:DetectLabels
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - translate:TranslateText
      Resource: '*'

functions:
  image-analyzis:
    handler: handler.main
    events:
      - http:
          path: analyse
          method: get
